version: '3'
services:
  docsify:
    privileged: true
    build: ./docker/docsify
    container_name: docsify_m141
    ports:
      - "10000:10000"
      - "35729:35729"
    volumes:
        - ./docs:/site
    working_dir: /site
    command: docsify serve . -p 10000 --livereload-port 35729

  plantuml:
    image: "plantuml/plantuml-server:jetty"
    container_name: plantuml_m141
    ports:
        - "10001:8080"

